# Enable C++ support
language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
install:
  #Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq g++-5; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$CXX" == "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

  #OS X
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew unlink wget; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install wget; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" == "gcc" ]; then export CC="gcc-4.9"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" == "gcc" ]; then export CXX="g++-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang

# Build steps
before_script:
  #Linux
    #SFML
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget http://www.sfml-dev.org/files/SFML-2.4.0-linux-gcc-64-bit.tar.gz; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xf SFML-2.4.0-linux-gcc-64-bit.tar.gz; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo cp -r SFML-2.4.0/lib/* /usr/local/lib/.; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo cp -r SFML-2.4.0/include/* /usr/local/include/.; fi
    #Lua
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install lua5.3; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install liblua5.3-dev; fi
    #OpenGL
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libglu1-mesa; fi
  #OS X
    #SFML
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget http://www.sfml-dev.org/files/SFML-2.4.0-osx-clang.tar.gz; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar xf SFML-2.4.0-osx-clang.tar.gz; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo cp -r SFML-2.4.0-osx-clang/lib/* /usr/local/lib/.; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo cp -r SFML-2.4.0-osx-clang/include/* /usr/local/include/.; fi
    #Lua
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install lua53; fi
    #OpenGL
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install fltk; fi
script:
  - mkdir build
  - cd build
  - cmake .. && make
