# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
before_script:
  - wget http://www.sfml-dev.org/files/SFML-2.4.0-linux-gcc-64-bit.tar.gz
  - tar xf SFML-2.4.0-linux-gcc-64-bit.tar.gz
  - sudo cp -r SFML-2.4.0/lib/* /usr/local/lib/.
  - sudo cp -r SFML-2.4.0/include/* /usr/local/include/.
script:
  - mkdir build
  - cd build
  - cmake .. && make
