# Enable C++ support
language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx
  - windows
  
#Environment variables
env:
  - LUA="lua=5.1"
  
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

    
# Build steps
before_script:
  #SFML
  - wget http://www.sfml-dev.org/files/SFML-2.4.0-linux-gcc-64-bit.tar.gz
  - tar xf SFML-2.4.0-linux-gcc-64-bit.tar.gz
  - sudo cp -r SFML-2.4.0/lib/* /usr/local/lib/.
  - sudo cp -r SFML-2.4.0/include/* /usr/local/include/.
  #Lua
  - sudo apt-get install lua5.1
  - sudo apt-get install liblua5.1-dev
  #OpenGL
  - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
script:
  - mkdir build
  - cd build
  - cmake .. && make
