# Enable C++ support
language: cpp
sudo: required
dist: trusty

os:
  - linux
  
compiler:
  - gcc
  - clang
install:
  - sudo apt-get install -qq g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang

# Build steps
before_script:
  #SFML
  - wget http://www.sfml-dev.org/files/SFML-2.4.0-linux-gcc-64-bit.tar.gz
  - tar xf SFML-2.4.0-linux-gcc-64-bit.tar.gz
  - sudo cp -r SFML-2.4.0/lib/* /usr/local/lib/.
  - sudo cp -r SFML-2.4.0/include/* /usr/local/include/.
  #Lua
  - sudo apt-get install lua5.1
  - sudo apt-get install liblua5.1-dev
  #OpenGL
  - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libglu1-mesa
script:
  - mkdir build
  - cd build
  - cmake .. && make
