# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
before_install:
  - sudo apt-get install libsfml-dev
script:
  - mkdir build
  - cd build
  - cmake .. && make
