# Enable C++ support
language: cpp

os:
  - linux
  - osx
  - windows

# Compiler selection
compiler:
  - clang
  - gcc
  
#Environment variables
env:
  - LUA="lua=5.1"
  
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
    
# Build steps
before_script:
  #SFML
  - wget http://www.sfml-dev.org/files/SFML-2.4.0-linux-gcc-64-bit.tar.gz
  - tar xf SFML-2.4.0-linux-gcc-64-bit.tar.gz
  - sudo cp -r SFML-2.4.0/lib/* /usr/local/lib/.
  - sudo cp -r SFML-2.4.0/include/* /usr/local/include/.
  #Lua
  - sudo apt-get install lua5.1
  - sudo apt-get install liblua5.1-dev
  #OpenGL
  - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
script:
  - mkdir build
  - cd build
  - cmake .. && make
